{% set name = "langchain-snowflake" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_snowflake-{{ version }}.tar.gz
    sha256: 51cc74e219a3fd2e83dea06917a4824d077531ca200d1c61e548740c4591fbc6
  - url: https://github.com/langchain-ai/langchain-snowflake/archive/refs/tags/libs/snowflake/v{{ version }}.tar.gz
    sha256: 0475d85a819d2a8f857cf962ef60413b1e32aa4f73bddc1153fe40ecb34de98f
    folder: gh_src

build:
  skip: true  # [py<39 or py>311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - langchain-core >=0.3.75,<0.4.0
    - snowflake >=0.8.0,<1.0
    - langchain >=0.3.27,<0.4.0
    - langgraph >=0.6.4,<0.7.0
    - langgraph-prebuilt >=0.6.4,<0.7.0
    - snowflake-snowpark-python >=1.20.0,<2.0.0
    - pydantic >=2.7.0,<3.0.0
    - aiohttp >=3.9.0,<4.0.0
    - langsmith >=0.4.21,<0.5.0
  run_constrained:
    - cryptography >=42.0.0,<43.0.0
    - mypy >=1.10,<2.0
    - types-requests >=2.31.0,<3.0.0

test:
  source_files:
    - gh_src/libs/snowflake/tests
  imports:
    - langchain_snowflake
    - langchain_snowflake._connection
    - langchain_snowflake._error_handling
    - langchain_snowflake.chat_models
    - langchain_snowflake.formatters
    - langchain_snowflake.retrievers
    - langchain_snowflake.tools
    - langchain_snowflake.tools._base
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v gh_src/libs/snowflake/tests
  requires:
    - pip
    - pytest >=7.4.3,<8.0.0

about:
  home: https://github.com/langchain-ai/langchain-snowflake
  summary: An integration package connecting Snowflake and LangChain
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/langchain-ai/langchain-snowflake
  doc_url: https://python.langchain.com/docs/integrations/document_loaders/snowflake
  description: This package contains the LangChain integration with Snowflake.

extra:
  recipe-maintainers:
    - Cansisti