{% set name = "langchain-snowflake" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_snowflake-{{ version }}.tar.gz
  sha256: bd9f99bed65cd7c0f889e63e21186a2444e6b3e4feabe362263ddfbd20dfdeb4

build:
  skip: True  # [py<39 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - langchain-core >=0.3.0,<0.4.0
    - snowflake >=0.8.0,<1.0

test:
  imports:
    - langchain_snowflake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-snowflake
  summary: An integration package connecting Snowflake and LangChain
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/langchain-ai/langchain-snowflake
  doc_url: https://github.com/langchain-ai/langchain-snowflake/blob/main/libs/snowflake/docs/retrievers.ipynb
  description: This package contains the LangChain integration with Snowflake.

extra:
  recipe-maintainers:
    - Cansisti
